### PR TITLE
add the possibility to add gas meter via reed contact

### PR DESCRIPTION
**Pull request by boskape**
is  it possible to add a gas meter via reed contact
also adding a start value

### CODE REVIEW

**Comment by DomiStyle** [comment]
Thanks, I assume these changes make it incompatible with the other providers?

**Comment by boskape** [comment]
sorry
i mean as addional sensor
because next to smartmeter often is the Gas Meter
and with a reed contact it counts the gas amount

i hope it is ok to add a link here as example
https://be-jo.net/2022/02/home-assistant-gaszaehler-mit-esphome-auslesen-flashen-unter-wsl/

if it is possible to do this on the same esp32 it will be helpfull

**Comment by DomiStyle** [comment]
Sure it's possible, just copy & paste the config from the site you linked into your meter config and connect the reed switch to one of the free GPIO ports.

However, you put this in as a pull request, not as an issue so I'm closing this for now.

**Comment by boskape** [comment]
Hi Dominik

Any idea why I get this errors


3:36:49
[E]
[espdm:373]
Unsupported OBIS data type
23:36:53
[I]
[espdm:397]
Received valid data
23:36:59
[I]
[espdm:397]
Received valid data
23:37:04
[I]
[espdm:397]
Received valid data
23:37:08
[E]
[espdm:121]
Unsupported OBIS header type
23:37:13
[E]
[espdm:081]
Payload length 2 is too big
23:37:19
[I]
[espdm:397]
Received valid data

Because sometimes it shows in the active Power Line strange values


Thx Peter

Von: Dominik ***@***.***>
Gesendet: Mittwoch, 31. August 2022 10:59
An: DomiStyle/esphome-dlms-meter ***@***.***>
Cc: Boska, Peter (SMO IT EMEA2 CE) ***@***.***>; Author ***@***.***>
Betreff: Re: [DomiStyle/esphome-dlms-meter] add the possibility to add gas meter via reed contact (PR #18)


Sure it's possible, just copy & paste the config from the site you linked into your meter config and connect the reed switch to one of the free GPIO ports.

However, you put this in as a pull request, not as an issue so I'm closing this for now.

-

**Pull request closed without merging**
